name: Renato Regli
favicon: null
layout_spectrum: 1
typography_spectrum: 0.00324
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.12266114540398121
  lightness: 0.45311872637830675
  saturation: 0.7085063715931028
  rhythmicContrast: 0.4754561521112919
purpose: []
